### ISSUE TITLE
Need a little help

### ISSUE THREAD

**Issue by frankeman90** [alextall/Transcode#1]
How do I move transcode-batch.sh to the right place in OSX (with terminal?).

I am now getting an error in Hazel, and am guessing that thats the problem? 

Have set up folder structure accordingly. Or is there any other paramters I should change as well?

Trying to convert an .mkv file and have installed makemkv.

**Comment by alextall** [comment]
@frankeman90 I'd like to close this issue. Is it safe to say we were able to resolve your issue?

**Comment by frankeman90** [comment]
Yes!

On Sun, May 29, 2016 at 10:53 AM -0700, "Alex" <notifications@github.com<mailto:notifications@github.com>> wrote:

@frankeman90https://github.com/frankeman90 I'd like to close this issue. Is it safe to say we were able to resolve your issue?

##
